"""empty message

Revision ID: 84ffaad552c0
Revises: f77d1aa64bbc
Create Date: 2020-10-25 15:06:53.765097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ffaad552c0'
down_revision = 'f77d1aa64bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('full_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'full_date')
    # ### end Alembic commands ###
