"""empty message

Revision ID: f77d1aa64bbc
Revises: 873f0e248d84
Create Date: 2020-10-24 23:36:49.738274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77d1aa64bbc'
down_revision = '873f0e248d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('days', sa.String(length=250), nullable=False))
    op.add_column('reminders', sa.Column('show_supplies', sa.Boolean(), nullable=False))
    op.add_column('reminders', sa.Column('supplies', sa.String(length=250), nullable=False))
    op.add_column('reminders', sa.Column('time', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'time')
    op.drop_column('reminders', 'supplies')
    op.drop_column('reminders', 'show_supplies')
    op.drop_column('reminders', 'days')
    # ### end Alembic commands ###
